#%RAML 1.0 DataType
displayName: ResourceDeletionError
type: ErrorObject
(builtinType): object
discriminatorValue: ResourceDeletion
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - ResourceDeletion
    required: true
  resource:
    type: any
    (builtinType): any
    required: false