#%RAML 1.0 DataType
displayName: ImportSink
type: object
(builtinType): object
examples:
  minimal:
    strict: true
    value: !include ../../examples/importsinks/ImportSink-minimal.json
description: |-
  An import sink is the entry point for import resources from other systems.
  
  It has an unique key and is specific to an import resource type.
  
  If needed you can specify a skip predicate, which allows you skip the import of
  operations which meet the conditions of the predicate.
properties:
  key:
    type: string
    (builtinType): string
    description: |-
      The unique key of the import sink.
    required: true
  resourceType:
    type: ImportResourceType
    (builtinType): string
    description: |-
      The type of import resource sent to this import sink.
      You can only send one resource type per import sink.
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The version of this resource.
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      When the import sink was created.
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      When the import sink was modified.
    required: true