#%RAML 1.0 DataType
displayName: ErrorObject
type: object
(builtinType): object
discriminator: code
(oneOf):
- AccessDeniedError
- ConcurrentModificationError
- ContentionError
- DuplicateAttributeValueError
- DuplicateAttributeValuesError
- DuplicateFieldError
- DuplicateVariantValuesError
- GenericError
- InsufficientScopeError
- InvalidCredentialsError
- InvalidFieldError
- InvalidInput
- InvalidJsonInput
- InvalidScopeError
- InvalidStateTransitionError
- InvalidTokenError
- RequiredFieldError
- ResourceCreationError
- ResourceDeletionError
- ResourceNotFoundError
- ResourceUpdateError
description: |-
  An error.
properties:
  code:
    type: string
    (builtinType): string
    required: true
  message:
    type: string
    (builtinType): string
    description: |-
      The error's description.
    required: true