#%RAML 1.0 DataType
displayName: InvalidTokenError
type: ErrorObject
(builtinType): object
discriminatorValue: invalid_token
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - invalid_token
    required: true