#%RAML 1.0 DataType
displayName: DiscountedLineItemPriceDraft
type: object
(builtinType): object
properties:
  value:
    type: Money
    (builtinType): object
    required: true
  includedDiscounts:
    type: array
    items:
      type: DiscountedLineItemPortion
    (builtinType): array
    required: true