#%RAML 1.0 DataType
displayName: DiscountedLineItemPortion
type: object
(builtinType): object
properties:
  discount:
    type: CartDiscountKeyReference
    (builtinType): object
    description: |-
      References a cart discount by its key.
    required: true
  discountedAmount:
    type: Money
    (builtinType): object
    required: true