#%RAML 1.0 DataType
displayName: ItemState
type: object
(builtinType): object
description: |-
  The item's state.
properties:
  quantity:
    type: number
    (builtinType): number
    required: true
  state:
    type: StateKeyReference
    (builtinType): object
    description: |-
      References a state by its key.
      
      The state referenced must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: true