#%RAML 1.0 DataType
displayName: ItemShippingTarget
type: object
(builtinType): object
description: |-
  Each item shipping target determines the address (as a reference to an address in `itemShippingAddresses`) 
  and the quantity that should be shipped to this address. Should multiple shipping addresses be needed 
  for one (custom) line item, sub-quantities are specified. Thus, an array of addresses and sub-quantities 
  is stored per (custom) line item. Upon order creation, the sum of sub-quantities must add up to the 
  total quantity of the (custom) line item.
properties:
  addressKey:
    type: string
    (builtinType): string
    description: |-
      The key of the address in the cart’s `itemShippingAddresses`
    required: true
  quantity:
    format: float
    type: number
    (builtinType): number
    description: |-
      The quantity of operations that should go to the address with the specified `addressKey`. 
      Only positive values are allowed. Using `0` as quantity is also possible in a draft object, 
      but the element will not be present in the resulting 
      [ItemShippingDetails](https://docs.commercetools.com/http-api-projects-carts.html#itemshippingdetails).
    required: true