#%RAML 1.0 DataType
displayName: ShippingInfoImportDraft
type: object
(builtinType): object
description: |-
  Maps to an order's `shippingInfo` property. This field is usually populated by the cart assosciated with
  the order, but when importing orders you must provide a draft representation as a part of the OrderImport.
properties:
  shippingMethodName:
    type: string
    (builtinType): string
    required: true
  price:
    type: Money
    (builtinType): object
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    description: |-
      The shipping rate used to determine the price.
    required: true
  taxRate:
    type: TaxRate
    (builtinType): object
    required: false
  taxCategory:
    type: TaxCategoryKeyReference
    (builtinType): object
    description: |-
      The tax category referenced must already exist
      in the commercetools project, or the
      import operation state is set to `Unresolved`.
    required: false
  shippingMethod:
    type: ShippingMethodKeyReference
    (builtinType): object
    description: |-
      Not set if a custom shipping method is used.
      
      The shipping method referenced must already exist 
      in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  deliveries:
    type: array
    items:
      type: Delivery
    (builtinType): array
    description: |-
      Deliveries are compilations of information on how the articles are being delivered to the customers.
    required: false
  discountedPrice:
    type: DiscountedLineItemPriceDraft
    (builtinType): object
    required: false
  shippingMethodState:
    type: ShippingMethodState
    (builtinType): string
    description: |-
      Indicates whether the 
      [ShippingMethod](https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingmethod) 
      referenced is allowed for the cart or not.
    required: false