#%RAML 1.0 DataType
displayName: TaxedPrice
type: object
(builtinType): object
properties:
  totalNet:
    type: Money
    (builtinType): object
    required: true
  totalGross:
    type: Money
    (builtinType): object
    required: true
  taxPortions:
    type: array
    items:
      type: TaxPortion
    (builtinType): array
    required: true