#%RAML 1.0 DataType
displayName: Attribute
type: object
(builtinType): object
discriminator: type
(oneOf):
- BooleanAttribute
- BooleanSetAttribute
- DateAttribute
- DateSetAttribute
- DateTimeAttribute
- DateTimeSetAttribute
- EnumAttribute
- EnumSetAttribute
- LocalizableEnumAttribute
- LocalizableEnumSetAttribute
- LocalizableTextAttribute
- LocalizableTextSetAttribute
- MoneyAttribute
- MoneySetAttribute
- NumberAttribute
- NumberSetAttribute
- ReferenceAttribute
- ReferenceSetAttribute
- TextAttribute
- TextSetAttribute
- TimeAttribute
- TimeSetAttribute
description: |-
  This type represents the value of an attribute of a product variant.
  The name and type property must match the name and type property of an attribute definition of the product type.
properties:
  name:
    type: string
    (builtinType): string
    description: |-
      The name of this attribute must match a name of the product types attribute definitions.
      The name is required if this type is used in a product variant and must not be set when
      used in a product variant patch.
    required: false
  type:
    type: string
    (builtinType): string
    required: true