# Resource
(resourceName): ByProjectKeyImportSinksByImportSinkKey
(resourcePathUri): /{projectKey}/import-sinks/{importSinkKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
  importSinkKey:
    type: string
    (builtinType): string
    description: |-
      The key of the import sink.
    required: true
put:
  description: |-
    Updates the import sink given by the key.
  body:
    application/json:
      type: ImportSinkDraft
      (builtinType): object
  responses:
    200:
      description: |-
        The import sink was successfully updated.
      body:
        application/json:
          type: ImportSink
          (builtinType): object
get:
  description: |-
    Retrieves the import sink given by the key.
  responses:
    200:
      description: |-
        The requested import sink was found.
      body:
        application/json:
          type: ImportSink
          (builtinType): object
delete:
  description: |-
    Deletes the import sink given by the key.
  responses:
    200:
      description: |-
        The deleted import sink.
      body:
        application/json:
          type: ImportSink
          (builtinType): object