#%RAML 1.0 DataType
displayName: EnumAttribute
type: Attribute
(builtinType): object
discriminatorValue: enum
description: |-
  This type represents an attribute which value is an enum.
  The attribute value refers to the key of the enum value.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - enum
    required: true
  value:
    type: string
    (builtinType): string
    required: true