#%RAML 1.0 DataType
displayName: LocalizableEnumAttribute
type: Attribute
(builtinType): object
discriminatorValue: lenum
description: |-
  This type represents an attribute which value is a localized enum.
  The attribute value refers to the key of the enum value.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - lenum
    required: true
  value:
    type: string
    (builtinType): string
    required: true