#%RAML 1.0 DataType
displayName: NumberAttribute
type: Attribute
(builtinType): object
discriminatorValue: number
description: |-
  This type represents an attribute which value is a number.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - number
    required: true
  value:
    type: number
    (builtinType): number
    required: true