#%RAML 1.0 DataType
displayName: TextAttribute
type: Attribute
(builtinType): object
discriminatorValue: text
description: |-
  This type represents an attribute which value is a string.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - text
    required: true
  value:
    type: string
    (builtinType): string
    required: true