#%RAML 1.0 DataType
displayName: PriceMapping
type: object
(builtinType): object
description: |-
  This type represents a mapping between the priceId and the priceKey.
properties:
  priceKey:
    type: string
    (builtinType): string
    description: |-
      The key of the imported price.
    required: true
  priceId:
    type: string
    (builtinType): string
    description: |-
      The ctp-id of the price.
    required: true
  productVariantKey:
    type: string
    (builtinType): string
    description: |-
      the variant key where the price is included
    required: true