#%RAML 1.0 DataType
displayName: Attributes
type: object
(builtinType): object
properties:
  //:
    type: Attribute | nil
    (oneOf):
    - Attribute
    - nil
    (builtinType): any
    description: |-
      The name of the attribute is given by the key and shouldn't be set on the attribute itself.
      And since this property will be represented as a map, we can set individual attributes to null
      to delete them (which follows JSON Merge Patch semantics).
    required: true