#%RAML 1.0 DataType
displayName: BooleanSetAttribute
type: Attribute
(builtinType): object
discriminatorValue: boolean-set
description: |-
  This type represents an attribute which value is set of boolean values.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - boolean-set
    required: true
  value:
    type: array
    items:
      type: boolean
    (builtinType): array
    required: true