#%RAML 1.0 DataType
displayName: DateAttribute
type: Attribute
(builtinType): object
discriminatorValue: date
description: |-
  This type represents an attribute which value is a date.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - date
    required: true
  value:
    type: date-only
    (builtinType): date-only
    required: true