#%RAML 1.0 DataType
displayName: LocalizableTextSetAttribute
type: Attribute
(builtinType): object
discriminatorValue: ltext-set
description: |-
  This type represents an attribute which value is a localized text.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ltext-set
    required: true
  value:
    type: array
    items:
      type: LocalizedString
    (builtinType): array
    required: true