#%RAML 1.0 DataType
displayName: MoneyAttribute
type: Attribute
(builtinType): object
discriminatorValue: money
description: |-
  This type represents an attribute which value is a money object.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - money
    required: true
  value:
    type: Money
    (builtinType): object
    required: true