#%RAML 1.0 DataType
displayName: TimeAttribute
type: Attribute
(builtinType): object
discriminatorValue: time
description: |-
  This type represents an attribute which value is a time.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - time
    required: true
  value:
    type: time-only
    (builtinType): time-only
    required: true