#%RAML 1.0 DataType
displayName: AssetDimensions
type: object
(builtinType): object
properties:
  w:
    type: number
    (builtinType): number
    required: true
  h:
    type: number
    (builtinType): number
    required: true