parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
  - plugin:react/recommended
  - plugin:testing-library/recommended
  - prettier
  - prettier/react
plugins:
  - import
  - jest
  - jsx-a11y
  - prettier
  - react
  - react-hooks
rules:
  react/jsx-tag-spacing: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  import/default: 0
  import/no-unresolved: 2
  'react-hooks/rules-of-hooks': 'error'
  'react-hooks/exhaustive-deps': 'warn'
settings:
  react:
    version: 'detect'
overrides:
  - files: ['*.spec.js']
    rules:
      'react/display-name': 0
