version: 2
snapshot:
  widths:
    - 1706
  min-height: 1024
  percy-css: |
    #application {
      height: auto;
    }
discovery:
  network-idle-timeout: 750 # ms (https://docs.percy.io/docs/command-line-client#section--network-idle-timeout-t)
