version: 2
snapshot:
  widths:
    - 1706
  min-height: 1024
  percy-css: |
    #application {
      height: auto;
    }
discovery:
  network-idle-timeout: 5000 # ms (https://docs.percy.io/docs/command-line-client#section--network-idle-timeout-t)
static:
  base-url: /
  files: "**/components/**/*.html,**/views/markdown/*.html,**/views/beta/*.html,**/releases/index.html,**/types/**/*.html,**/endpoints/**/*.html,**/layouts/**/*.html"
  ignore: "**/site-template/**/*.html"
