nodeLinker: node-modules

packageExtensions:
  lmdb@^2.5.3:
    dependencies:
      cbor-x: ^1.5.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: 'https://raw.githubusercontent.com/emmenko/yarn-plugin-postinstall/nm-fix-no-postinstall/bundles/%40yarnpkg/plugin-postinstall.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

postinstall: ./scripts/postinstall.sh

yarnPath: .yarn/releases/yarn-4.7.0.cjs
