module.exports = {
  excludedKeywords: [
    '/getting-started#sign-up',
    '/login',
    '/http-api',
    '/graphql-api',
    '/release-notes',
    '/software-development-kits',
    '/cli-overview',
    '/import-api',
    '/sunrise',
    '/tutorials-overview',
    '/custom-applications',
    '/faqs',
    '/merchant-center',
    '/merchant-center-releases',
    '/privacy',
    '/imprint',
  ],
};
