#%RAML 1.0
---
title: Commercetools Test API Spec
version: v0.1 beta
mediaType: application/json
baseUri: https://subdomain-{exampleUriParameter}.example.com
baseUriParameters:
  exampleUriParameter:
    enum:
      - subdomainOne
      - subdomainTwo
      - subdomainThree
    description: |
      Free text description of the uri parameter.
securitySchemes:
  oauth_2_0: !include security-schemes/oauth2.raml
securedBy: [ oauth_2_0 ]


# This API represents a series of test cases from which to generate API documentation

uses:
  objects: types/objects.raml

# Endpoints ("Resources" in RAML and HTTP terminology)
# Every CT API endpoint starts at this root
/{projectKey}:
  uriParameters:
    projectKey:
      description: The CTP project key.
      type: string
  /resource:
    post:
      displayName: Create a Resource
      description: Create (POST) operation to a resource.
      securedBy:
        - oauth_2_0:
            scopes: ["manage_test:{projectKey}"]
      body:
        type: objects.ObjectTestTypeDraft
      responses:
        201:
          description: 201 Created response. This is the success response when creating something.
          body:
            type: objects.ObjectTestType
