# Resource
(resourceName): ByProjectKeyUnresolvedImportResourceById
(resourcePathUri): /{projectKey}/unresolved-import-resource/{id}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  id:
    type: string
    (builtinType): string
    description: |-
      The unresolved resource id, which is the equal to the operationId.
    required: true
delete:
  description: |-
    Deletes the unresolved resource with the given id.
  responses:
    200:
      body:
        application/json:
          type: UnresolvedImportResource
          (builtinType): object
get:
  description: |-
    Retrievees the unresolved resource with the given `operationId`.
  responses:
    200:
      body:
        application/json:
          type: UnresolvedImportResource
          (builtinType): object