# Resource
(resourceName): ByProjectKeyPriceMapping
(resourcePathUri): /{projectKey}/price-mapping

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
post:
  description: |-
    Creates or updates the price-mapping given in the body.
  body:
    application/json:
      type: PriceMapping
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: PriceMapping
          (builtinType): object