#%RAML 1.0 DataType
displayName: ImportResourceType
description: |-
  The type of the import resource.
type: string
enum:
- category
- order
- price
- product
- product-type
- product-variant
- product-variant-patch
(enumDescriptions):
  category: "The category import resource type."
  order: "The order import resource type."
  price: "The price import resource type."
  product: "The product import resource type."
  product-type: "The product type import resource type."
  product-variant: "The product variant import resource type."
  product-variant-patch: "The product variant patch import resource type."