#%RAML 1.0 DataType
displayName: AttributeNumberType
type: AttributeType
(builtinType): object
discriminatorValue: number
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - number
    required: true