#%RAML 1.0 DataType
displayName: AttributeTimeType
type: AttributeType
(builtinType): object
discriminatorValue: time
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - time
    required: true