#%RAML 1.0
---
title: Commercetools Test API Spec
annotationTypes:
  resourceName:
    type: string
    allowedTargets: [Resource, Method]
  resourcePathUri:
    type: string
    allowedTargets: [Resource, Method]
  builtinType:
    type: string
    allowedTargets: TypeDeclaration
  oneOf:
    type: array
    items: string
    allowedTargets: TypeDeclaration
  enumDescriptions:
     type: object
     (builtinType): object
     description: |-
       Describes the values of an enum type.
  beta:
     type: boolean
     (builtinType): boolean
     description: |-
       if true, designates that the element is not released yet like regular elements and should be treated as being subject to
       changes, incompleteness and ongoing development.
       Documentation must provide a hint that the element is in beta status and can opt to hide such elements.
       If not set, false must be assumed.
  deprecated:
     type: boolean
     (builtinType): boolean
     description: |-
       If true, designates that the element carrying this annotation should not be used any more and is subject to potential later removal.
       If used, the description text should explain the new way the effect of the deprecated element is to be achieved.
       If not set, false must be assumed.
       Documentation can choose to hide deprecated elements, mark them deprecated or make them less prominent as needed.
       Documentation must not suppress the fact that an element is deprecated.
  refersTo:
     type: string
     (builtinType): string
     description: |-
       Must contain either a type name in the current API or a detectable addressing scheme like URN or URL pointing to other entities.
       if the `refersTo` annotation is used on a RAML element it designates that the element is referring, linking or pointing to another type of entity.
       Documentation should generate a navigatable link to that other entity.
securitySchemes:
  oauth_2_0: !include oauth2.raml
securedBy:
- oauth_2_0
types:
  AnnotationsTestType: !include types/AnnotationsTestType.raml
  AnyPropertiesType: !include types/AnyPropertiesType.raml
  AnyTestType: !include types/AnyTestType.raml
  ArrayTestType: !include types/ArrayTestType.raml
  BooleanTestType: !include types/BooleanTestType.raml
  ChangeSomePropertyOnExampleResource: !include types/ChangeSomePropertyOnExampleResource.raml
  ConstantLikeType: !include types/ConstantLikeType.raml
  DateTestType: !include types/DateTestType.raml
  DoSomeThingOnExampleResource: !include types/DoSomeThingOnExampleResource.raml
  EnumPropertiesType: !include types/EnumPropertiesType.raml
  EnumTest: !include types/EnumTest.raml
  EnumWithDescriptionExample: !include types/EnumWithDescriptionExample.raml
  ExampleResourceUpdate: !include types/ExampleResourceUpdate.raml
  ExampleResourceUpdateAction: !include types/ExampleResourceUpdateAction.raml
  ExampleTargetType: !include types/ExampleTargetType.raml
  ExampleTargetTypeKeyReference: !include types/ExampleTargetTypeKeyReference.raml
  ExampleTargetTypePointer: !include types/ExampleTargetTypePointer.raml
  ExampleTargetTypeReference: !include types/ExampleTargetTypeReference.raml
  ExampleTargetTypeResourceIdentifier: !include types/ExampleTargetTypeResourceIdentifier.raml
  ExamplesTestType: !include types/ExamplesTestType.raml
  FloatTestType: !include types/FloatTestType.raml
  ImportFooForSecondPropertyToUpdateOnExampleResource: !include types/ImportFooForSecondPropertyToUpdateOnExampleResource.raml
  IntegerTestType: !include types/IntegerTestType.raml
  KeyReference: !include types/KeyReference.raml
  NumberTestType: !include types/NumberTestType.raml
  ObjectTestType: !include types/ObjectTestType.raml
  ObjectTestTypeDraft: !include types/ObjectTestTypeDraft.raml
  OptionalPropertyTestType: !include types/OptionalPropertyTestType.raml
  OutOfOrderPropertiesTestType: !include types/OutOfOrderPropertiesTestType.raml
  Reference: !include types/Reference.raml
  ReferenceTypeId: !include types/ReferenceTypeId.raml
  ReferencesTestType: !include types/ReferencesTestType.raml
  RegexPropertiesType: !include types/RegexPropertiesType.raml
  ResourceIdentifier: !include types/ResourceIdentifier.raml
  SetOfEnumTestType: !include types/SetOfEnumTestType.raml
  SingleExampleTestType: !include types/SingleExampleTestType.raml
  SingleFullExampleTestType: !include types/SingleFullExampleTestType.raml
  StringTestType: !include types/StringTestType.raml
  UnionLikeSubType1: !include types/UnionLikeSubType1.raml
  UnionLikeSubType2: !include types/UnionLikeSubType2.raml
  UnionLikeType: !include types/UnionLikeType.raml
  
/{projectKey}: !include resources/ByProjectKey.raml
/{projectKey}/resource: !include resources/ByProjectKeyResource.raml
/{projectKey}/resource/artificially-complex/path/uri-parameter-one={uriParameterOne}/{uriParameterTwo}: !include resources/ByProjectKeyResourceArtificiallyComplexPathUriParameterOneByUriParameterOneByUriParameterTwo.raml
/{projectKey}/resource/key={key}: !include resources/ByProjectKeyResourceKeyByKey.raml
/{projectKey}/resource/searchApiPattern: !include resources/ByProjectKeyResourceSearchApiPattern.raml
/{projectKey}/resource/{id}: !include resources/ByProjectKeyResourceById.raml