#%RAML 1.0 DataType
displayName: Asset
type: object
(builtinType): object
properties:
  key:
    type: string
    (builtinType): string
    description: |-
      User-defined identifier for the asset.
      Asset keys are unique inside their container (a product variant or a category).
    required: true
  sources:
    minItems: 1
    type: array
    items:
      type: AssetSource
    (builtinType): array
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  tags:
    type: array
    items:
      type: string
    (builtinType): array
    required: false