#%RAML 1.0 DataType
displayName: CartDiscountKeyReference
type: KeyReference
(builtinType): object
discriminatorValue: cart-discount
description: |-
  References a cart discount by its key.
properties:
  typeId:
    type: ReferenceType
    (builtinType): string
    description: |-
      The type of the referenced resource.
    enum:
    - cart-discount
    required: true