#%RAML 1.0 DataType
displayName: ImportResource
type: object
(builtinType): object
(oneOf):
- CategoryImport
- PriceImport
- ProductImport
- ProductTypeImport
- ProductVariantImport
description: |-
  A representation of the resource to import.
  Import resources are similar to commercetools draft types, but they only support key references.
  In general, import resources are more granular then the normal commercetools resource.
  They are optimized for incremental updates and therefore have a slightly different structure.
properties:
  key:
    type: string
    (builtinType): string
    required: true