#%RAML 1.0 DataType
displayName: PriceImport
type: ImportResource
(builtinType): object
description: |-
  Imports a product variant's prices.
properties:
  key:
    type: string
    (builtinType): string
    required: true
  value:
    type: Money
    (builtinType): object
    description: |-
      Maps to `Price.value`.
      
      The Import API **only** supports `centPrecision` prices.
    required: true
  country:
    pattern: "^[A-Z]{2}$"
    type: CountryCode
    (builtinType): string
    description: |-
      Maps to `Price.county`.
    required: false
  validFrom:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      Maps to `Price.validFrom`.
    required: false
  validUntil:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      Maps to `Price.validUntil`.
    required: false
  customerGroup:
    type: CustomerGroupKeyReference
    (builtinType): object
    description: |-
      References a customer group by its key. 
      
      The customer group referenced
      must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  channel:
    type: ChannelKeyReference
    (builtinType): object
    description: |-
      References a channel by its key. 
      
      The channel referenced
      must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  productVariant:
    type: ProductVariantKeyReference
    (builtinType): object
    description: |-
      The product variant in which this price is contained.
      
      The product variant referenced
      must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: true
  product:
    type: ProductKeyReference
    (builtinType): object
    description: |-
      The product in which this product variant containong the price is contained. Maps to `ProductVariant.product`.
      
      The product referenced
      must already exist in the commercetools project, or the
      import operation state is set to `Unresolved`.
    required: true