# Resource
(resourceName): ByProjectKeyResourceById
(resourcePathUri): /{projectKey}/resource/{id}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
    required: true
  id:
    type: string
    (builtinType): string
    required: true
post:
  displayName: Update a Resource by ID
  description: |-
    Update a resource by ID
  body:
    application/json:
      type: ExampleResourceUpdate
      (builtinType): object
      examples:
        default:
          strict: true
          value: !include ../examples/ByProjectKeyResourceByIdPost-default.json

get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
      - "view_test:{projectKey}"
  displayName: Get a Resource by its ID
  description: |-
    Query by ID
  queryParameters:
    optionalQueryParameter:
      required: false
      type: string
      (builtinType): string
      description: |-
        This is a query parameter.
      examples:
        default:
          strict: true
          value: "optional"
    secondOptionalQueryParameter:
      required: false
      type: string
      (builtinType): string
      description: |-
        This is another query parameter.
      examples:
        default:
          strict: true
          value: "second optional"
  responses:
    200:
      body:
        application/json:
          type: ObjectTestType
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyResourceByIdGet-200-default.json

delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
  displayName: Delete a Resource by its ID
  description: |-
    Deletes a resource.
  responses:
    200:
      description: |-
        Deletion was successful.
      body:
        application/json:
          type: ObjectTestType
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyResourceByIdDelete-200-default.json
