# Resource
(resourceName): ByProjectKeyResource
(resourcePathUri): /{projectKey}/resource

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
    required: true
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
  displayName: Create a Resource
  description: |-
    Create (POST) operation to a resource.
  body:
    application/json:
      type: ObjectTestTypeDraft
      (builtinType): object
      examples:
        default:
          strict: true
          value: !include ../examples/ByProjectKeyResourcePost-default.json

  responses:
    201:
      description: |-
        201 Created response. This is the success response when creating something.
      body:
        application/json:
          type: ObjectTestType
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyResourcePost-201-default.json

get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
      - "view_test:{projectKey}"
  displayName: Get all resources
  description: |-
    Query/retrieve (GET) a specific resource or resource(s). This should return a paged query result of _blah_.
  queryParameters:
    where:
      required: false
      type: string
      (builtinType): string
      examples:
        default:
          strict: true
          value: "6 in arrayOfIntExample"
    sort:
      required: false
      type: string
      (builtinType): string
      examples:
        default:
          strict: true
          value: "DESC"
    expand:
      required: false
      type: string
      (builtinType): string
      examples:
        default:
          strict: true
          value: "arrayOfObjectType[*]"
    limit:
      required: false
      format: float
      type: number
      (builtinType): number
      examples:
        default:
          strict: true
          value: 50
    offset:
      required: false
      format: float
      type: number
      (builtinType): number
      examples:
        default:
          strict: true
          value: 5
    collection:
      required: false
      type: ObjectTestType
      (builtinType): object
      description: |-
        A typical Object type with a non-scalar property.
  responses:
    200:
      description: |-
        A 200 response.  This is the case when reading or modifying something.
      body:
        application/json:
          type: ArrayTestType
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyResourceGet-200-default.json
