# Resource
(resourceName): ByProjectKeyResource
(resourcePathUri): /{projectKey}/resource

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
    required: true
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
  displayName: Create a Resource
  description: |-
    Create (POST) operation to a resource.
  body:
    application/json:
      type: ObjectTestTypeDraft
      (builtinType): object
      examples:
        default:
          strict: true
          value: !include ../examples/ByProjectKeyResourcePost-default.json

  responses:
    201:
      description: |-
        201 Created response. This is the success response when creating something.
      body:
        application/json:
          type: ObjectTestType
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyResourcePost-201-default.json

  (codeExamples):
    curl: |-
      curl -X POST https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/resource -i \
      --header 'Authorization: Bearer ${BEARER_TOKEN}' \
      --header 'Content-Type: application/json' \
      --data-binary @- << DATA 
      {
        "objectTypeProperty" : {
          "arrayOfIntExample" : [ 1, 2, 1, 3, 2, 3, 1 ],
          "arrayOfUniqueIntExample" : [ 1, 3, 5, 7 ],
          "arrayOfTwonumbersExample" : [ 3, 5 ],
          "arrayOfFloatExample" : [ 0.82 ],
          "arrayOfNumberNoDefaultsExample" : [ 10, 9, 8, 7, 6 ],
          "arrayOfStringExample" : [ "dog", "cat", "bird" ],
          "arrayOfObjectType" : [ {
            "integerExample" : 777,
            "integerExampleInt32" : 1
          }, {
            "integerExample" : 30000,
            "integerExampleInt32" : 22
          } ]
        }
      }
      DATA
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
      - "view_test:{projectKey}"
  displayName: Get all resources
  description: |-
    Query/retrieve (GET) a specific resource or resource(s). This should return a paged query result of _blah_.
  queryParameters:
    stringParameter:
      required: false
      type: string
      (builtinType): string
      examples:
        default:
          strict: true
          value: "6 in arrayOfIntExample"
    floatParameter:
      required: false
      format: float
      type: number
      (builtinType): number
      examples:
        default:
          strict: true
          value: 50
    integerParameter:
      required: false
      format: int
      type: integer
      (builtinType): integer
      examples:
        default:
          strict: true
          value: 50
    withMarkdownDescription:
      required: false
      format: float
      type: number
      (builtinType): number
      description: |-
        This `markdown` should be parsed correctly.
      examples:
        default:
          strict: true
          value: 50
    objectParameter:
      required: false
      type: ObjectTestType
      (builtinType): object
      description: |-
        A typical Object type with a non-scalar property.
    arrayOfObject:
      required: false
      type: array
      items:
        type: ObjectTestType
      (builtinType): array
  responses:
    200:
      description: |-
        A 200 response.  This is the case when reading or modifying something.
      body:
        application/json:
          type: ArrayTestType
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyResourceGet-200-default.json

  (codeExamples):
    curl: |-
      curl -X GET https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/resource -i \
      --header 'Authorization: Bearer ${BEARER_TOKEN}'
