#%RAML 1.0 DataType
displayName: ProductImport
type: ImportResource
(builtinType): object
description: |-
  Import representation for a prduct.
  
  The import representation for a product is the most minimal representation required
  for creating a product in commercetools.
properties:
  key:
    type: string
    (builtinType): string
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    description: |-
      Maps to `Product.name`.
    required: true
  productType:
    type: ProductTypeKeyReference
    (builtinType): object
    description: |-
      The product's product type. Maps to `Product.productType`.
      
      The product type referenced
      must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    description: |-
      Human-readable identifiers usually used as deep-link URL to the related product. Each slug must be unique across a project,
      but a product can have the same slug for different languages. Allowed are alphabetic, numeric, underscore (_) and hyphen (-) characters.
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    description: |-
      Maps to `Product.description`.
    required: false
  categories:
    type: array
    items:
      type: CategoryKeyReference
    (builtinType): array
    description: |-
      An array of references to a categories by their keys. Maps to `Product.categories`. 
      
      The categories referenced
      must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  metaTitle:
    type: LocalizedString
    (builtinType): object
    required: false
  metaDescription:
    type: LocalizedString
    (builtinType): object
    required: false
  metaKeywords:
    type: LocalizedString
    (builtinType): object
    required: false
  taxCategory:
    type: TaxCategoryKeyReference
    (builtinType): object
    description: |-
      References a tax category by its key.
      
      The tax category referenced must already exist 
      in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  searchKeywords:
    type: SearchKeywords
    (builtinType): object
    required: false
  state:
    type: StateKeyReference
    (builtinType): object
    description: |-
      References a state by its key.
      
      The tax category referenced must already exist 
      in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false