version: 2.1

aliases:
  - &working_directory ~/commercetools-docs-kit

  - &restore_yarn_cache
    restore_cache:
      name: 'Restoring yarn cache'
      keys:
        - v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-yarn-cache-{{ .Branch }}
        - v1-yarn-cache

  - &save_yarn_cache
    save_cache:
      name: 'Saving yarn cache'
      key: v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

  - &run_yarn
    run: yarn --frozen-lockfile

executors:
  node_10:
    working_directory: *working_directory
    docker:
      - image: circleci/node:10.17

commands:
  setup_dependencies:
    description: Installing dependencies
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
  lint_and_test:
    description: Running linters and tests
    steps:
      - run:
          name: Running linters and tests
          command: yarn run jest --projects jest.{eslint,stylelint,test}.config.js --maxWorkers=3 --reporters jest-silent-reporter
  build_websites:
    description: Building websites for production
    steps:
      - run: yarn build
  save_websites_bundle:
    steps:
      - persist_to_workspace:
          root: *working_directory
          paths:
            - public/
  restore_websites_bundle:
    steps:
      - attach_workspace:
          at: *working_directory

jobs:
  build_lint_and_test:
    executor: node_10
    steps:
      - setup_dependencies
      - *save_yarn_cache
      - lint_and_test
      - build_websites
      - save_websites_bundle

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_lint_and_test
