#%RAML 1.0
---
title: Commercetools Importer API
annotationTypes:
  resourceName:
    type: string
    allowedTargets: [Resource, Method]
  resourcePathUri:
    type: string
    allowedTargets: [Resource, Method]
  builtinType:
    type: string
    allowedTargets: TypeDeclaration
  oneOf:
    type: array
    items: string
    allowedTargets: TypeDeclaration
securitySchemes:
  oauth_2_0: !include oauth2.raml
securedBy:
- oauth_2_0
baseUri: https://import.commercetools.com
types:
  AccessDeniedError: !include types/errors/AccessDeniedError.raml
  Address: !include types/common/Address.raml
  Asset: !include types/common/Asset.raml
  AssetDimensions: !include types/common/AssetDimensions.raml
  AssetSource: !include types/common/AssetSource.raml
  Attribute: !include types/productvariants/Attribute.raml
  AttributeBooleanType: !include types/producttypes/AttributeBooleanType.raml
  AttributeConstraintEnum: !include types/producttypes/AttributeConstraintEnum.raml
  AttributeDateTimeType: !include types/producttypes/AttributeDateTimeType.raml
  AttributeDateType: !include types/producttypes/AttributeDateType.raml
  AttributeDefinition: !include types/producttypes/AttributeDefinition.raml
  AttributeEnumType: !include types/producttypes/AttributeEnumType.raml
  AttributeLocalizableTextType: !include types/producttypes/AttributeLocalizableTextType.raml
  AttributeLocalizedEnumType: !include types/producttypes/AttributeLocalizedEnumType.raml
  AttributeLocalizedEnumValue: !include types/producttypes/AttributeLocalizedEnumValue.raml
  AttributeMoneyType: !include types/producttypes/AttributeMoneyType.raml
  AttributeNestedType: !include types/producttypes/AttributeNestedType.raml
  AttributeNumberType: !include types/producttypes/AttributeNumberType.raml
  AttributePlainEnumValue: !include types/producttypes/AttributePlainEnumValue.raml
  AttributeReferenceType: !include types/producttypes/AttributeReferenceType.raml
  AttributeSetType: !include types/producttypes/AttributeSetType.raml
  AttributeTextType: !include types/producttypes/AttributeTextType.raml
  AttributeTimeType: !include types/producttypes/AttributeTimeType.raml
  AttributeType: !include types/producttypes/AttributeType.raml
  Attributes: !include types/productvariants/Attributes.raml
  BooleanAttribute: !include types/productvariants/BooleanAttribute.raml
  BooleanSetAttribute: !include types/productvariants/BooleanSetAttribute.raml
  CartDiscountKeyReference: !include types/common/CartDiscountKeyReference.raml
  CategoryImport: !include types/categories/CategoryImport.raml
  CategoryImportRequest: !include types/importrequests/CategoryImportRequest.raml
  CategoryKeyReference: !include types/common/CategoryKeyReference.raml
  ChannelKeyReference: !include types/common/ChannelKeyReference.raml
  ConcurrentModificationError: !include types/errors/ConcurrentModificationError.raml
  ContentionError: !include types/errors/ContentionError.raml
  CountryCode: !include types/CountryCode.raml
  CurrencyCode: !include types/CurrencyCode.raml
  CustomTokenizer: !include types/products/CustomTokenizer.raml
  CustomerGroupKeyReference: !include types/common/CustomerGroupKeyReference.raml
  CustomerKeyReference: !include types/common/CustomerKeyReference.raml
  DateAttribute: !include types/productvariants/DateAttribute.raml
  DateSetAttribute: !include types/productvariants/DateSetAttribute.raml
  DateTimeAttribute: !include types/productvariants/DateTimeAttribute.raml
  DateTimeSetAttribute: !include types/productvariants/DateTimeSetAttribute.raml
  DuplicateAttributeValueError: !include types/errors/DuplicateAttributeValueError.raml
  DuplicateAttributeValuesError: !include types/errors/DuplicateAttributeValuesError.raml
  DuplicateFieldError: !include types/errors/DuplicateFieldError.raml
  DuplicateVariantValuesError: !include types/errors/DuplicateVariantValuesError.raml
  EnumAttribute: !include types/productvariants/EnumAttribute.raml
  EnumSetAttribute: !include types/productvariants/EnumSetAttribute.raml
  EnumValue: !include types/common/EnumValue.raml
  ErrorObject: !include types/errors/ErrorObject.raml
  ErrorResponse: !include types/errors/ErrorResponse.raml
  GenericError: !include types/errors/GenericError.raml
  Image: !include types/common/Image.raml
  ImportOperation: !include types/importoperations/ImportOperation.raml
  ImportOperationPagedResponse: !include types/importoperations/ImportOperationPagedResponse.raml
  ImportOperationState: !include types/importoperations/ImportOperationState.raml
  ImportOperationStatus: !include types/importoperations/ImportOperationStatus.raml
  ImportRequest: !include types/importrequests/ImportRequest.raml
  ImportResource: !include types/common/ImportResource.raml
  ImportResourceType: !include types/common/ImportResourceType.raml
  ImportResponse: !include types/importrequests/ImportResponse.raml
  ImportSink: !include types/importsinks/ImportSink.raml
  ImportSinkDraft: !include types/importsinks/ImportSinkDraft.raml
  ImportSinkPagedResponse: !include types/importsinks/ImportSinkPagedResponse.raml
  ImportSummary: !include types/importsummaries/ImportSummary.raml
  InsufficientScopeError: !include types/errors/InsufficientScopeError.raml
  InvalidCredentialsError: !include types/errors/InvalidCredentialsError.raml
  InvalidFieldError: !include types/errors/InvalidFieldError.raml
  InvalidInput: !include types/errors/InvalidInput.raml
  InvalidJsonInput: !include types/errors/InvalidJsonInput.raml
  InvalidScopeError: !include types/errors/InvalidScopeError.raml
  InvalidStateTransitionError: !include types/errors/InvalidStateTransitionError.raml
  InvalidTokenError: !include types/errors/InvalidTokenError.raml
  KeyReference: !include types/common/KeyReference.raml
  LocalizableEnumAttribute: !include types/productvariants/LocalizableEnumAttribute.raml
  LocalizableEnumSetAttribute: !include types/productvariants/LocalizableEnumSetAttribute.raml
  LocalizableTextAttribute: !include types/productvariants/LocalizableTextAttribute.raml
  LocalizableTextSetAttribute: !include types/productvariants/LocalizableTextSetAttribute.raml
  LocalizedEnumValue: !include types/common/LocalizedEnumValue.raml
  LocalizedString: !include types/common/LocalizedString.raml
  Money: !include types/common/Money.raml
  MoneyAttribute: !include types/productvariants/MoneyAttribute.raml
  MoneySetAttribute: !include types/productvariants/MoneySetAttribute.raml
  NumberAttribute: !include types/productvariants/NumberAttribute.raml
  NumberSetAttribute: !include types/productvariants/NumberSetAttribute.raml
  OperationStates: !include types/importsummaries/OperationStates.raml
  PriceImport: !include types/prices/PriceImport.raml
  PriceImportRequest: !include types/importrequests/PriceImportRequest.raml
  PriceKeyReference: !include types/common/PriceKeyReference.raml
  ProcessingState: !include types/common/ProcessingState.raml
  ProductImport: !include types/products/ProductImport.raml
  ProductImportRequest: !include types/importrequests/ProductImportRequest.raml
  ProductKeyReference: !include types/common/ProductKeyReference.raml
  ProductTypeImport: !include types/producttypes/ProductTypeImport.raml
  ProductTypeImportRequest: !include types/importrequests/ProductTypeImportRequest.raml
  ProductTypeKeyReference: !include types/common/ProductTypeKeyReference.raml
  ProductVariantImport: !include types/productvariants/ProductVariantImport.raml
  ProductVariantImportRequest: !include types/importrequests/ProductVariantImportRequest.raml
  ProductVariantKeyReference: !include types/common/ProductVariantKeyReference.raml
  ProductVariantPatch: !include types/productvariants/ProductVariantPatch.raml
  ProductVariantPatchRequest: !include types/importrequests/ProductVariantPatchRequest.raml
  ReferenceAttribute: !include types/productvariants/ReferenceAttribute.raml
  ReferenceSetAttribute: !include types/productvariants/ReferenceSetAttribute.raml
  ReferenceType: !include types/common/ReferenceType.raml
  RequiredFieldError: !include types/errors/RequiredFieldError.raml
  ResourceCreationError: !include types/errors/ResourceCreationError.raml
  ResourceDeletionError: !include types/errors/ResourceDeletionError.raml
  ResourceNotFoundError: !include types/errors/ResourceNotFoundError.raml
  ResourceUpdateError: !include types/errors/ResourceUpdateError.raml
  SearchKeyword: !include types/products/SearchKeyword.raml
  SearchKeywords: !include types/products/SearchKeywords.raml
  ShippingMethodKeyReference: !include types/common/ShippingMethodKeyReference.raml
  StateKeyReference: !include types/common/StateKeyReference.raml
  SubRate: !include types/prices/SubRate.raml
  SuggestTokenizer: !include types/products/SuggestTokenizer.raml
  TaxCategoryKeyReference: !include types/common/TaxCategoryKeyReference.raml
  TaxRate: !include types/prices/TaxRate.raml
  TextAttribute: !include types/productvariants/TextAttribute.raml
  TextInputHint: !include types/producttypes/TextInputHint.raml
  TextSetAttribute: !include types/productvariants/TextSetAttribute.raml
  TimeAttribute: !include types/productvariants/TimeAttribute.raml
  TimeSetAttribute: !include types/productvariants/TimeSetAttribute.raml
  VariantValues: !include types/errors/VariantValues.raml
  WhitespaceTokenizer: !include types/products/WhitespaceTokenizer.raml
  
/{projectKey}: !include resources/ByProjectKey.raml
/{projectKey}/categories: !include resources/ByProjectKeyCategories.raml
/{projectKey}/categories/importSinkKey={importSinkKey}: !include resources/ByProjectKeyCategoriesImportSinkKeyByImportSinkKey.raml
/{projectKey}/categories/importSinkKey={importSinkKey}/import-operations: !include resources/ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperations.raml
/{projectKey}/categories/importSinkKey={importSinkKey}/import-operations/{id}: !include resources/ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsById.raml
/{projectKey}/categories/importSinkKey={importSinkKey}/resourceKey={resourceKey}: !include resources/ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyResourceKeyByResourceKey.raml
/{projectKey}/import-sinks: !include resources/ByProjectKeyImportSinks.raml
/{projectKey}/import-sinks/{importSinkKey}: !include resources/ByProjectKeyImportSinksByImportSinkKey.raml
/{projectKey}/import-summaries: !include resources/ByProjectKeyImportSummaries.raml
/{projectKey}/import-summaries/importSinkKey={importSinkKey}: !include resources/ByProjectKeyImportSummariesImportSinkKeyByImportSinkKey.raml
/{projectKey}/prices: !include resources/ByProjectKeyPrices.raml
/{projectKey}/prices/importSinkKey={importSinkKey}: !include resources/ByProjectKeyPricesImportSinkKeyByImportSinkKey.raml
/{projectKey}/prices/importSinkKey={importSinkKey}/import-operations: !include resources/ByProjectKeyPricesImportSinkKeyByImportSinkKeyImportOperations.raml
/{projectKey}/prices/importSinkKey={importSinkKey}/import-operations/{id}: !include resources/ByProjectKeyPricesImportSinkKeyByImportSinkKeyImportOperationsById.raml
/{projectKey}/prices/importSinkKey={importSinkKey}/resourceKey={resourceKey}: !include resources/ByProjectKeyPricesImportSinkKeyByImportSinkKeyResourceKeyByResourceKey.raml
/{projectKey}/product-types: !include resources/ByProjectKeyProductTypes.raml
/{projectKey}/product-types/importSinkKey={importSinkKey}: !include resources/ByProjectKeyProductTypesImportSinkKeyByImportSinkKey.raml
/{projectKey}/product-types/importSinkKey={importSinkKey}/import-operations: !include resources/ByProjectKeyProductTypesImportSinkKeyByImportSinkKeyImportOperations.raml
/{projectKey}/product-types/importSinkKey={importSinkKey}/import-operations/{id}: !include resources/ByProjectKeyProductTypesImportSinkKeyByImportSinkKeyImportOperationsById.raml
/{projectKey}/product-types/importSinkKey={importSinkKey}/resourceKey={resourceKey}: !include resources/ByProjectKeyProductTypesImportSinkKeyByImportSinkKeyResourceKeyByResourceKey.raml
/{projectKey}/product-types/importSinkKey={importSinkKey}/resourceKey={resourceKey}/import-operation: !include resources/ByProjectKeyProductTypesImportSinkKeyByImportSinkKeyResourceKeyByResourceKeyImportOperation.raml
/{projectKey}/product-variant-patches: !include resources/ByProjectKeyProductVariantPatches.raml
/{projectKey}/product-variant-patches/importSinkKey={importSinkKey}: !include resources/ByProjectKeyProductVariantPatchesImportSinkKeyByImportSinkKey.raml
/{projectKey}/product-variant-patches/importSinkKey={importSinkKey}/import-operations: !include resources/ByProjectKeyProductVariantPatchesImportSinkKeyByImportSinkKeyImportOperations.raml
/{projectKey}/product-variant-patches/importSinkKey={importSinkKey}/import-operations/{id}: !include resources/ByProjectKeyProductVariantPatchesImportSinkKeyByImportSinkKeyImportOperationsById.raml
/{projectKey}/product-variant-patches/importSinkKey={importSinkKey}/resourceKey={resourceKey}: !include resources/ByProjectKeyProductVariantPatchesImportSinkKeyByImportSinkKeyResourceKeyByResourceKey.raml
/{projectKey}/product-variants: !include resources/ByProjectKeyProductVariants.raml
/{projectKey}/product-variants/importSinkKey={importSinkKey}: !include resources/ByProjectKeyProductVariantsImportSinkKeyByImportSinkKey.raml
/{projectKey}/product-variants/importSinkKey={importSinkKey}/import-operations: !include resources/ByProjectKeyProductVariantsImportSinkKeyByImportSinkKeyImportOperations.raml
/{projectKey}/product-variants/importSinkKey={importSinkKey}/import-operations/{id}: !include resources/ByProjectKeyProductVariantsImportSinkKeyByImportSinkKeyImportOperationsById.raml
/{projectKey}/product-variants/importSinkKey={importSinkKey}/resourceKey={resourceKey}: !include resources/ByProjectKeyProductVariantsImportSinkKeyByImportSinkKeyResourceKeyByResourceKey.raml
/{projectKey}/product-variants/importSinkKey={importSinkKey}/resourceKey={resourceKey}/import-operation: !include resources/ByProjectKeyProductVariantsImportSinkKeyByImportSinkKeyResourceKeyByResourceKeyImportOperation.raml
/{projectKey}/products: !include resources/ByProjectKeyProducts.raml
/{projectKey}/products/importSinkKey={importSinkKey}: !include resources/ByProjectKeyProductsImportSinkKeyByImportSinkKey.raml
/{projectKey}/products/importSinkKey={importSinkKey}/import-operations: !include resources/ByProjectKeyProductsImportSinkKeyByImportSinkKeyImportOperations.raml
/{projectKey}/products/importSinkKey={importSinkKey}/import-operations/{id}: !include resources/ByProjectKeyProductsImportSinkKeyByImportSinkKeyImportOperationsById.raml
/{projectKey}/products/importSinkKey={importSinkKey}/resourceKey={resourceKey}: !include resources/ByProjectKeyProductsImportSinkKeyByImportSinkKeyResourceKeyByResourceKey.raml