#%RAML 1.0 DataType
displayName: AttributeNestedType
type: AttributeType
(builtinType): object
discriminatorValue: nested
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - nested
    required: true
  typeReference:
    type: ProductTypeKeyReference
    (builtinType): object
    description: |-
      References a product type by its key.
    required: true