#%RAML 1.0 DataType
displayName: AttributePlainEnumValue
type: object
(builtinType): object
properties:
  key:
    type: string
    (builtinType): string
    required: true
  label:
    type: string
    (builtinType): string
    required: true