#%RAML 1.0 DataType
displayName: AttributeDateTimeType
type: AttributeType
(builtinType): object
discriminatorValue: datetime
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - datetime
    required: true