#%RAML 1.0 DataType
displayName: AttributeDateType
type: AttributeType
(builtinType): object
discriminatorValue: date
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - date
    required: true