#%RAML 1.0 DataType
displayName: AttributeEnumType
type: AttributeType
(builtinType): object
discriminatorValue: enum
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - enum
    required: true
  values:
    type: array
    items:
      type: AttributePlainEnumValue
    (builtinType): array
    required: true