#%RAML 1.0 DataType
displayName: ProductTypeImport
type: ImportResource
(builtinType): object
description: |-
  Import representation for a product type.
properties:
  key:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    description: |-
      Maps to `ProductType.name`.
    required: true
  description:
    type: string
    (builtinType): string
    description: |-
      Maps to `ProductType.description`.
    required: true
  attributes:
    type: array
    items:
      type: AttributeDefinition
    (builtinType): array
    description: |-
      The product type's attributes.
    required: false