#%RAML 1.0 Library
usage: Enum test types.

uses:
  annotations: ../annotation-types/annotations.raml

types:
  EnumTest:
    description: Example enumeration for the SetOfEnumTestTypes type.
    type: string
    enum:
      - EnumEntryOne
      - EnumEntryTwo
      - EnumEntryThree
  EnumPropertiesType:
    description: Test data for properties with enums that are of differing primitive types
    properties:
      intWithEnumExample:
        description: An int with enum values
        type: integer
        enum: [ 1, 2, 3 ]
      floatWithEnumExample:
        description: A float with enum values
        type: number
        format: float
        default: 1.0
        enum: [ 1.0, 2.0, 3.0 ]
      enumOfStringExample:
        description: A string with enum values (undescribed)
        type: string
        enum:
          - "dog"
          - "cat"
          - "elephant"
        default: "dog"
  SetOfEnumTestType:
    description: A type containing a property with a set of Enums
    # I.e. how `ChannelDraft` has `ChannelRole`s
    properties:
      setofEnumExample:
        description: |
          Contains a Set of `EnumTest`. If `uniqueItems` is `true` for an Array,
          the then instead of "Array of ______", it needs to read "Set of _______".
        type: EnumTest[]
        uniqueItems: true
  EnumWithDescriptionExample:
    description: Enum with agreed upon description annotation.
    type: string
    (annotations.enumDescriptions):
      enumValue1: description 1
      enumValue2: description 2
      enumWithMarkdownDescription: |
        `inline-code` should be formatted as an inline code. [ObjectTestType](/types/general#objecttesttype) should link to the header of the definition of `ObjectTestType` on this website - `api-docs-smoke-test`. [Links](/../docs-smoke-test/views/markdown#links) should link to the header for the definition of  `Links` on `docs-smoke-test` microsite.
    enum:
      - enumValue1
      - enumValue2
      - enumWithoutDescription
      - enumWithMarkdownDescription
  EnumGroupExample1:
    description: Example enumeration for the SetOfEnumTestTypes type.
    type: string
    enum:
      - enumValue1
      - enumValue2
      - enumValue3
      - enumValue4
      - enumValue5
      - enumValue6
      - enumValue7
    (annotations.enumGroups):
      enumValue1: |
        description of enumValue1
      enumValue2: |
        description of enumValue2. `inline-code` should be formatted as an inline code.
      enumValue3: |
        description of enumValue3
      enumValue4: |
        description of enumValue4
      enumValue5: |
        description of enumValue5
      enumValue6: |
        description of enumValue6
      enumValue7: |
        description of enumValue7
  EnumGroupExample2:
    description: Example enumeration for the SetOfEnumTestTypes type.
    type: string
    enum:
      - enumValue8
      - enumValue9
      - enumValue10
      - enumValue11
      - enumValue12
      - enumValue13
      - enumValue14
    (annotations.enumGroups):
      enumValue8: |
        description of enumValue8
      enumValue9: |
        description of enumValue9. `inline-code` should be formatted as an inline code.
      enumValue10: |
        description of enumValue10
      enumValue11: |
        description of enumValue11
      enumValue12: |
        description of enumValue12
      enumValue13: |
        description of enumValue13
      enumValue14: |
        description of enumValue14