#%RAML 1.0 Library
usage: External link test type.

uses:
  exampleForManualTypeLinks: example-for-manual-type-links.raml

types:
  ExternalLinkTestType:
    properties:
      isExternalType:
        description: A link pointing to a type in another website.
        type: exampleForManualTypeLinks.ExampleForManualTypeLinks
