# Resource
(resourceName): ByProjectKeyImportOperation
(resourcePathUri): /{projectKey}/import-operation

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
put:
  description: |-
    Updates an import operation given in the body.
  body:
    application/json:
      type: ImportOperationDraft
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: ImportOperation
          (builtinType): object
post:
  description: |-
    Creates or updates the import operation given in the body.
  body:
    application/json:
      type: ImportOperationDraft
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: ImportOperation
          (builtinType): object
get:
  description: |-
    Retrieves all import operations for the given import sink.
  queryParameters:
    limit:
      required: false
      type: number
      (builtinType): number
    offset:
      required: false
      type: number
      (builtinType): number
    resourceKey:
      required: false
      type: string
      (builtinType): string
      description: |-
        The key of the import operation to retrieve.
    importSinkKey:
      required: false
      type: string
      (builtinType): string
      description: |-
        The key of the import operation to retrieve.
    state:
      required: false
      type: ProcessingState
      (builtinType): string
      description: |-
        The state of the import operations to retrieve.
  responses:
    200:
      body:
        application/json:
          type: ImportOperationPagedResponse
          (builtinType): object