# Resource
(resourceName): ByProjectKeyResourceArtificiallyComplexPathUriParameterOneByUriParameterOneByUriParameterTwo
(resourcePathUri): /{projectKey}/resource/artificially-complex/path/uri-parameter-one={uriParameterOne}/{uriParameterTwo}
description: |-
  Artificial Endpoint constructing a high complexity of what could theoretically come together in one API

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
    required: true
  uriParameterOne:
    type: string
    (builtinType): string
    description: |-
      A Path parameter in the equal-sign-pseudo-query notation
    required: true
  uriParameterTwo:
    type: string
    (builtinType): string
    description: |-
      A Path parameter as a plain variable path element
    required: true
post:
  description: |-
    Updates the resource. OutOfOrderPropertiesTestType is used because it is big and long.
  queryParameters:
    queryParameterOne:
      required: false
      format: float
      type: number
      (builtinType): number
      description: |-
        some parameter to construct a combination of URI and query params
    queryParameterTwo:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: OutOfOrderPropertiesTestType
      (builtinType): object
  responses:
    200:
      description: |-
        ArrayTestType is used because it is big and long.
      body:
        application/json:
          type: ArrayTestType
          (builtinType): object
    202:
      description: |-
        DateTestType is used because it is big and long
        This is not used by commercetools but a valid 2xx response that says that it will process the stuff later.
        It's here to check how we handle multiple "OK" style response options.
      body:
        application/json:
          type: DateTestType
          (builtinType): object