# Resource
(resourceName): ByProjectKeyResourceKeyByKey
(resourcePathUri): /{projectKey}/resource/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_test:{projectKey}"
      - "view_test:{projectKey}"
  displayName: Get a Resource by its Key
  description: |-
    Query by key. Has three responses to see the difference between modeling patterns in RAML
  responses:
    200:
      description: |-
        this is directly using a named type without messing with it, thats how we want to use RAML
      body:
        application/json:
          type: ObjectTestType
          (builtinType): object