#%RAML 1.0 DataType
displayName: CustomLineItemDraft
type: object
(builtinType): object
properties:
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  quantity:
    type: number
    (builtinType): number
    required: true
  money:
    type: Money
    (builtinType): object
    required: true
  slug:
    type: string
    (builtinType): string
    required: true
  taxCategory:
    type: TaxCategoryKeyReference
    (builtinType): object
    description: |-
      References a tax category by its key.
    required: false
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false