#%RAML 1.0 DataType
displayName: Delivery
type: object
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true
  parcels:
    type: array
    items:
      type: Parcel
    (builtinType): array
    required: true
  address:
    type: Address
    (builtinType): object
    required: false