#%RAML 1.0 DataType
displayName: LineItemImportDraft
type: object
(builtinType): object
description: |-
  Represents an individual line item in an Order. A line item is a snapshot of a product at the time it was added to the order. 
  
  You cannot create an order which includes line operations that do not exist in the project or have been deleted. 
  Products and variants referenced by a line item must already exist in the commercetools project.
properties:
  name:
    type: LocalizedString
    (builtinType): object
    description: |-
      Maps to `LineItem.name`.
    required: true
  variant:
    type: ProductVariantKeyReference
    (builtinType): object
    description: |-
      References a product variant. Maps to `LineItem.variant`.
      
      The product variant referenced (and therefore, the product)
      must already exist in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: true
  price:
    type: PriceImport
    (builtinType): object
    description: |-
      Maps to `LineItem.price`.
    required: true
  quantity:
    format: float
    type: number
    (builtinType): number
    description: |-
      Maps to `LineItem.quantity`.
    required: true
  state:
    type: array
    items:
      type: ItemState
    (builtinType): array
    required: false
  supplyChannel:
    type: ChannelKeyReference
    (builtinType): object
    description: |-
      References a supply channel. Maps to `LineItem.supplyChannel`.
      
      The supply channel referenced must already exist 
      in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  distributionChannel:
    type: ChannelKeyReference
    (builtinType): object
    description: |-
      References a distribution channel. Maps to `LineItem.distributionChannel`.
      
      The distribution channel referenced must already exist 
      in the commercetools project, or the 
      import operation state is set to `Unresolved`.
    required: false
  taxRate:
    type: TaxRate
    (builtinType): object
    description: |-
      Maps to `LineItem.taxRate`.
    required: false
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    description: |-
      Maps to LineItem.shippingDetails.
    required: false