#%RAML 1.0 DataType
displayName: ParcelMeasurements
type: object
(builtinType): object
properties:
  heightInMillimeter:
    type: number
    (builtinType): number
    required: false
  lengthInMillimeter:
    type: number
    (builtinType): number
    required: false
  widthInMillimeter:
    type: number
    (builtinType): number
    required: false
  weightInGram:
    type: number
    (builtinType): number
    required: false