#%RAML 1.0 DataType
displayName: ShippingRatePriceTier
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartClassificationTier
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    required: true