#%RAML 1.0 DataType
displayName: TrackingData
type: object
(builtinType): object
properties:
  trackingId:
    type: string
    (builtinType): string
    required: false
  carrier:
    type: string
    (builtinType): string
    required: false
  provider:
    type: string
    (builtinType): string
    required: false
  providerTransaction:
    type: string
    (builtinType): string
    required: false
  isReturn:
    type: boolean
    (builtinType): boolean
    required: false