#%RAML 1.0 DataType
displayName: EnumPropertiesType
type: object
(builtinType): object
description: |-
  Test data for properties with enums that are of differing primitive types
properties:
  intWithEnumExample:
    format: float
    type: number
    (builtinType): number
    description: |-
      An int with enum values
    enum:
    - 1
    - 2
    - 3
    required: true
  floatWithEnumExample:
    format: float
    type: number
    (builtinType): number
    description: |-
      A float with enum values
    enum:
    - 1.0
    - 2.0
    - 3.0
    default: 1.0
    required: true
  enumOfStringExample:
    type: string
    (builtinType): string
    description: |-
      A string with enum values (undescribed)
    enum:
    - dog
    - cat
    - elephant
    required: true