#%RAML 1.0 DataType
displayName: ExampleResourceUpdate
type: object
(builtinType): object
properties:
  version:
    format: float
    type: number
    (builtinType): number
    description: |-
      The expected version of the ExampleResource on which the changes should be applied.
      If the expected version does not match the actual version, a 409 Conflict will be returned.
    required: true
  actions:
    type: array
    items:
      type: ExampleResourceUpdateAction
    (builtinType): array
    description: |-
      The list of update actions to be performed on the ExampleResource.
      Actions are applied in the given order.
    required: true