#%RAML 1.0 DataType
displayName: ExamplesTestType
type: object
(builtinType): object
examples:
  fullExample: !include ../examples/ExamplesTestType-fullExample.json
  fullExampleInRamlNotation: !include ../examples/ExamplesTestType-fullExampleInRamlNotation.json
  fullExampleWithLoosenedStrict: !include ../examples/ExamplesTestType-fullExampleWithLoosenedStrict.json
  simpleExample: !include ../examples/ExamplesTestType-simpleExample.json
properties:
  foo:
    type: string
    (builtinType): string
    required: true
  baz:
    type: integer
    (builtinType): integer
    required: true
  boo:
    type: boolean
    (builtinType): boolean
    required: true