#%RAML 1.0 DataType
displayName: UnresolvedReference
type: object
(builtinType): object
description: |-
  A reference that an unresolved resource might be waiting for
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      An artificial id for the unresolved reference, to accomodate our database model
    required: true
  referenceKey:
    type: string
    (builtinType): string
    description: |-
      The expected reference key
    required: true
  referenceType:
    type: ReferenceType
    (builtinType): string
    description: |-
      The expected reference type
    required: true
  importSinkKey:
    type: string
    (builtinType): string
    description: |-
      The key of the import sink
    required: true
  operationId:
    type: string
    (builtinType): string
    description: |-
      The operation identifier from which the orginal resource resulted
    required: true