#%RAML 1.0 DataType
displayName: AnnotationsTestType
type: object
(builtinType): object
properties:
  isBetaType:
    type: string
    (builtinType): string
    description: |-
      Beta property. If true, a "beta" flag should appear beside the type name.
    (beta): true
    required: true
  isDeprecatedType:
    type: string
    (builtinType): string
    description: |-
      Deprecated property. THIS MUST NOT BE RENDERED AT ALL (=hidden in documentation, it just stays there to keep SDKs backwards compatible).
    (deprecated): true
    required: true
