#%RAML 1.0 DataType
displayName: AnyPropertiesType
type: object
(builtinType): object
description: |-
  This is a type that can have arbitrary properties
properties:
  //:
    type: string
    (builtinType): string
    required: true
