#%RAML 1.0 DataType
displayName: BooleanTestType
type: object
(builtinType): object
properties:
  booleanExample:
    type: boolean
    (builtinType): boolean
    description: |-
      Description text including rendered `markdown`.
    default: true
    required: true
