#%RAML 1.0 DataType
displayName: ConstantLikeProperties
type: object
(builtinType): object
description: |-
  Has properties that are constant-like, that is, enums with only one value.
properties:
  stringConstantLike:
    type: string
    (builtinType): string
    description: |-
      a string contant-like property
    enum:
    - constantStringValue
    required: true
  intConstantLike:
    format: int
    type: integer
    (builtinType): integer
    description: |-
      an integer contant-like property
    enum:
    - 256
    required: true
  floatConstantLike:
    format: float
    type: number
    (builtinType): number
    description: |-
      a float contant-like property
    enum:
    - 3.14
    required: true
