#%RAML 1.0 DataType
displayName: Do SomeThing
type: ExampleResourceUpdateAction
(builtinType): object
discriminatorValue: doSomeThing
examples:
  default:
    strict: true
    value: !include ../examples/DoSomeThingOnExampleResource-default.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - doSomeThing
    required: true
