#%RAML 1.0 DataType
displayName: Do SomeThing
type: ExampleResourceUpdateAction
(builtinType): object
discriminatorValue: doSomeThing
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - doSomeThing
    required: true