#%RAML 1.0 DataType
displayName: EnumWithDescriptionExample
description: |-
  Enum with agreed upon description annotation.
type: string
enum:
- enumValue1
- enumValue2
- enumWithoutDescription
(enumDescriptions):
  enumValue1: "description 1"
  enumValue2: "description 2"
