#%RAML 1.0 DataType
displayName: EnumWithDescriptionExample
description: |-
  Enum with agreed upon description annotation.
type: string
enum:
- value1
- value2
- value3
(enumDescriptions):
  value1: "description 1"
  value2: "description 2"
  value3: "description 3"