#%RAML 1.0 DataType
displayName: Reference
type: Reference
(builtinType): object
discriminatorValue: example-target
(refersTo): "ExampleTargetType"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    description: |-
      The allowed typeIds of the referenced resource.
    enum:
    - example-target
    required: true
  obj:
    type: IntegerTestType
    (builtinType): object
    description: |-
      This is a type which contains test data for Integer properties.
    required: true
