#%RAML 1.0 DataType
displayName: Import Foo for SecondPropertyToUpdate
type: ExampleResourceUpdateAction
(builtinType): object
discriminatorValue: importFooForSecondPropertyToUpdate
description: |-
  Another Update action for ExampleResource that needs crazy long name
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - importFooForSecondPropertyToUpdate
    required: true
  secondPropertyToUpdate:
    type: string
    (builtinType): string
    required: true
