#%RAML 1.0 DataType
displayName: NumberTestType
type: object
(builtinType): object
description: |-
  Tests JSON type "number",
properties:
  numberExample:
    type: number
    (builtinType): number
    required: true
