#%RAML 1.0 DataType
displayName: ReferenceTypeId
description: |-
  The allowed typeIds of the referenced resource.
type: string
enum:
- example-target
- cart-discount
- category
- channel
- customer
- customer-group
- price
- product
- product-type
- product-variant
- shipping-method
- state
- tax-category
(enumDescriptions):
  example-target: "References an ExampleTargetType."
  cart-discount: "References a cart discount."
  category: "References a category."
  channel: "References a channel."
  customer: "References a customer."
  customer-group: "References a customer group."
  price: "References a price."
  product: "References a product."
  product-type: "References a product type."
  product-variant: "References a product variant."
  shipping-method: "References a shipping method."
  state: "References a state."
  tax-category: "References a tax-category."