#%RAML 1.0 DataType
displayName: SingleFullExampleTestType
(builtinType): string
type: string


examples:
  default:
    displayName: Full Example
    description: |-
      This **markdown** formatted description of the code example is to be shown with it.
      The title of this example must be "Full Example" (displayName overrides the name).
      The JSON contained must be code highlighted because the mime type is set.
    strict: false
    value: !include ../examples/SingleFullExampleTestType-default.json
