#%RAML 1.0 DataType
displayName: UnionLikeSubType2
type: UnionLikeType
(builtinType): object
discriminatorValue: value2
description: |-
  This specific instance of the union is rendered like a regular type with a property table
properties:
  kind:
    type: EnumWithDescriptionExample
    (builtinType): string
    description: |-
      Enum with agreed upon description annotation.
    enum:
    - value2
    required: true
  bar:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true
