#%RAML 1.0 DataType
displayName: UnionLikeSubTypeWithEnumDescriptionProperties3
type: UnionLikeWithEnumDescriptionPropertiesInSubtype
(builtinType): object
discriminatorValue: enumWithoutDescription
description: |-
  The discriminatorValue (value2) of this union like sub stype is defined in EnumWithDescriptionExample but without a description.
properties:
  type:
    type: EnumWithDescriptionExample
    (builtinType): string
    description: |-
      Enum with agreed upon description annotation.
    enum:
    - enumWithoutDescription
    required: true
    (inherited): true
  baz:
    type: string
    (builtinType): string
    required: true
    (inherited): false
  name:
    type: string
    (builtinType): string
    required: true
    (inherited): false
