#%RAML 1.0 DataType
displayName: UnionLikeSubType2
type: UnionLikeType
(builtinType): object
discriminatorValue: subtype2
description: |-
  This specific instance of the union is rendered like a regular type with a property table
properties:
  kind:
    type: string
    (builtinType): string
    enum:
    - subtype2
    required: true
  bar:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true
