#%RAML 1.0 DataType
displayName: WideLayoutArrayTestType
type: object
(builtinType): object
examples:
  default:
    strict: true
    value: !include ../examples/WideLayoutArrayTestType-default.json
description: |-
  A copy of ArrayTestType, used to test wide layout.
properties:
  arrayOfIntExample:
    uniqueItems: false
    minItems: 1
    type: array
    items:
      type: integer
    (builtinType): array
    description: |-
      A property with an array of ints. JSON primitive is `array`, display type is "Array of Int".
    required: true
    (inherited): false
  arrayOfUniqueIntExample:
    uniqueItems: true
    minItems: 1
    type: array
    items:
      type: integer
    (builtinType): array
    description: |-
      A property with an array of ints in which items must be unique. JSON primitive is `array`, display type is "Array of Int"
    required: true
    (inherited): false
  arrayOfTwonumbersExample:
    minItems: 2
    maxItems: 2
    type: array
    items:
      type: integer
    (builtinType): array
    required: true
    (inherited): false
  arrayOfFloatExample:
    uniqueItems: false
    minItems: 1
    maxItems: 1
    type: array
    items:
      format: float
      type: number
    (builtinType): array
    description: |-
      An array of float. JSON primitive is `array`, display type is "Array of Float". !!! Until underlying libraries are fixed, this displays "Array of Number" because the pattern information is lost.
    required: true
    (inherited): false
  arrayOfNumberNoDefaultsExample:
    type: array
    items:
      type: number
    (builtinType): array
    description: |-
      An array of float. JSON primitive is `array`, display type is "Array of Number"
    required: true
    (inherited): false
  arrayOfStringExample:
    uniqueItems: false
    type: array
    items:
      type: string
    (builtinType): array
    description: |-
      An array of strings. JSON primitive is `array`, display type is "Array of String"
    required: true
    (inherited): false
  arrayOfObjectType:
    uniqueItems: false
    type: array
    items:
      type: IntegerTestType
    (builtinType): array
    description: |-
      An array of IntegerTestType. JSON primitive is `array`, display type is "Array of IntegerTestType"
    required: true
    (inherited): false
