#%RAML 1.0 DataType
displayName: ImportMessage
type: object
(builtinType): object
description: |-
  this types represents the import messages that circulates between internal queues
properties:
  headers:
    type: ImportMessageHeaders
    (builtinType): object
    description: |-
      the message headers
    required: true
  data:
    type: any
    (builtinType): any
    description: |-
      The type of the import resource sent to this import sink.
    required: true