#%RAML 1.0 DataType
displayName: CustomTokenizer
type: SuggestTokenizer
(builtinType): object
discriminatorValue: custom
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - custom
    required: true
  inputs:
    type: array
    items:
      type: string
    (builtinType): array
    required: true