# Resource
(resourceName): ByProjectKeyProductTypesImportSinkKeyByImportSinkKeyResourceKeyByResourceKey
(resourcePathUri): /{projectKey}/product-types/importSinkKey={importSinkKey}/resourceKey={resourceKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
  importSinkKey:
    type: string
    (builtinType): string
    description: |-
      The import sink used to create the new resource
    required: true
  resourceKey:
    type: string
    (builtinType): string
    required: true
delete:
  description: |-
    Deletes the product type given by the resource key.