# Resource
(resourceName): ByProjectKeyCategories
(resourcePathUri): /{projectKey}/categories

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
