# Resource
(resourceName): ByProjectKeyImportSinks
(resourcePathUri): /{projectKey}/import-sinks

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
post:
  description: |-
    Creates a new import sink.
  body:
    application/json:
      type: ImportSinkDraft
      (builtinType): object
  responses:
    201:
      body:
        application/json:
          type: ImportSink
          (builtinType): object
get:
  description: |-
    Retrieves all import sinks of a project key.
  queryParameters:
    limit:
      required: true
      type: number
      (builtinType): number
    offset:
      required: true
      type: number
      (builtinType): number
  responses:
    200:
      body:
        application/json:
          type: ImportSinkPagedResponse
          (builtinType): object