# Resource
(resourceName): ByProjectKey
(resourcePathUri): /{projectKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
