#%RAML 1.0 Library

types:
  AnyTestType:
    description: Tests acceptance of JSON blobs.
    properties:
      anyTypeExample:
        description: A test of type "any", i.e. any JSON allowed here. To be displayed as "any JSON".
        type: any
