#%RAML 1.0 Library

# Making constant values explicit is more usable so we render this pattern differnt than a regular Enum:

types:
  ConstantLikeType:
    type: string
    description: render an enum with one value as a constant.
    enum: [constantExampleValue]
