#%RAML 1.0 Library

types:
  RegexPropertiesType:
    description: This is a type that can have arbitrary properties as long as they match a certain expression
    type: object
    properties:
      /^[a-z]{2}(-[A-Z]{2})?$/:
        type: string
