#%RAML 1.0 Library
usage: Unions test types.

# Not supporting actual RAML Union types, only a pattern that has a parent without own properties except the discriminator

uses:
  enums: enums.raml

types:
  UnionLikeType:
    description: |
      A pattern of inheritance that is to be represented like a union, i.e. this parent type would not be shown with a property list on its own.
    type: object
    discriminator: kind
    properties:
      kind: enums.EnumWithDescriptionExample
  UnionLikeSubType1:
    description: This specific instance of the union is rendered like a regular type with a property table
    type: UnionLikeType
    discriminatorValue: value1
    properties:
      foo: string
      name: string
  UnionLikeSubType2:
    description: This specific instance of the union is rendered like a regular type with a property table
    type: UnionLikeType
    discriminatorValue: value2
    properties:
      bar: string
      name: string
