#%RAML 1.0 DataType
displayName: DuplicateAttributeValuesError
type: ErrorObject
(builtinType): object
discriminatorValue: DuplicateAttributeValues
description: |-
  The CombinationUnique AttributeConstraint was violated.
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DuplicateAttributeValues
    required: true
  attributes:
    type: array
    items:
      type: Attribute
    (builtinType): array
    required: true