#%RAML 1.0 DataType
displayName: DuplicateVariantValuesError
type: ErrorObject
(builtinType): object
discriminatorValue: DuplicateVariantValues
description: |-
  A given combination of variant values conflicts with an existing one.
  Every product variant must have a distinct combination of SKU, prices, and custom attribute values.
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DuplicateVariantValues
    required: true
  variantValues:
    type: VariantValues
    (builtinType): object
    description: |-
      The offending variant values.
    required: true