#%RAML 1.0 DataType
displayName: ErrorResponse
type: object
(builtinType): object
description: |-
  The response in case of an error.
properties:
  statusCode:
    format: int
    type: integer
    (builtinType): integer
    description: |-
      The http status code of the response.
    required: true
  message:
    type: string
    (builtinType): string
    description: |-
      Describes the error.
    required: true
  error:
    type: string
    (builtinType): string
    description: |-
      This property is only used for OAuth2 errors.
      Contains the error code.
    required: false
  error_description:
    type: string
    (builtinType): string
    description: |-
      This property is only used for OAuth2 errors.
      Additional information to assist the client developer in
      understanding the error.
    required: false
  errors:
    type: array
    items:
      type: ErrorObject
    (builtinType): array
    description: |-
      The errors that caused this error response.
    required: false