#%RAML 1.0 DataType
displayName: InvalidCredentialsError
type: ErrorObject
(builtinType): object
discriminatorValue: InvalidCredentials
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidCredentials
    required: true