#%RAML 1.0 DataType
displayName: RequiredFieldError
type: ErrorObject
(builtinType): object
discriminatorValue: RequiredField
description: |-
  A required field is missing a value.
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - RequiredField
    required: true
  field:
    type: string
    (builtinType): string
    description: |-
      The name of the field.
    required: true