#%RAML 1.0 DataType
displayName: ImportRequestState
type: object
(builtinType): object
description: |-
  Allows to retrieve the state of an ImportRequest.
properties:
  operations:
    maxItems: 20
    type: array
    items:
      type: ImportOperation
    (builtinType): array
    required: true